# Generated by Django 5.2.10 on 2026-01-24 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(default='2025-2026', max_length=9)),
                ('salary_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('filing_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_app.taxpayerprofile')),
            ],
        ),
    ]
